# Environment variables can be used in the config file by wrapping them in ${ENV_NAME} syntax.

# Enables verbose and readable output for the console log. Otherwise, json is used.
human_readable_log: true

# It is recommended to use separate user for the bot.
gitlab_token: ${GITLAB_TOKEN} # ref: https://gitlab.com/-/profile/personal_access_tokens

slack_bot_token: ${SLACK_BOT_TOKEN} # ref: https://api.slack.com/authentication/token-types#bot
slack_app_token: ${SLACK_APP_TOKEN} # ref: https://api.slack.com/authentication/token-types#app

# Database connection.
mongo:
  host: ${MONGO_HOST}
  port: ${MONGO_PORT}
  user: ${MONGO_USER}
  pass: ${MONGO_PASS}
  db: ${MONGO_DB}

# How often the bot should scan through all MRs
pull_period: 14m30s